import { Link } from "react-router-dom";
import { ArrowRight } from "lucide-react";
import SiteHeader from "@/components/SiteHeader";

export default function About() {
  return <main className="min-h-screen bg-[#f5f8f9] text-[#17223b]">
    <section className="bg-gradient-to-br from-[#263bd0] via-[#293fd7] to-[#182a9f] text-white">
      <SiteHeader />
      <div className="mx-auto max-w-5xl px-5 pb-20 pt-32 text-center sm:px-8 sm:pt-40"><h1 className="mx-auto max-w-4xl text-[38px] font-extrabold leading-[1.05] tracking-[-0.06em] sm:text-[62px]">About<br /><span className="text-[#5de1d3]">PureListVerifier</span></h1><p className="mx-auto mt-6 max-w-2xl text-base leading-6 text-blue-100">We are committed to helping businesses maintain clean email lists and protect their sender reputation.</p></div>
    </section>
    
    <section className="mx-auto max-w-5xl px-5 py-16 sm:px-8 sm:py-20"><div className="grid items-center gap-10 lg:grid-cols-[1.1fr_0.9fr]"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#3155e8]">Built for better sends</p><h2 className="mt-3 text-3xl font-extrabold tracking-[-0.04em]">Our mission is simple: make every address count.</h2><p className="mt-4 max-w-2xl text-sm leading-6 text-[#71809d]">PureListVerifier was founded to solve one simple problem: email deliverability. We help marketing teams, businesses, and agencies clean their email lists to improve campaign performance and protect domain reputation.</p></div><div className="grid grid-cols-2 gap-3"><div className="rounded-2xl bg-[#182a9f] p-5 text-white"><p className="text-2xl font-extrabold">99.9%</p><p className="mt-1 text-xs text-blue-200">platform uptime</p></div><div className="rounded-2xl bg-[#22b7bd] p-5 text-white"><p className="text-2xl font-extrabold">24/7</p><p className="mt-1 text-xs text-teal-50">automated checks</p></div></div></div></section>

    <section className="bg-[#eef3ff] px-5 py-16 sm:px-8 sm:py-20"><div className="mx-auto max-w-5xl"><div className="text-center"><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#3155e8]">How it works</p><h2 className="mt-3 text-3xl font-extrabold tracking-[-0.04em]">A cleaner workflow in three steps</h2></div><div className="mt-10 grid gap-5 md:grid-cols-3"><div className="rounded-2xl bg-white p-6 shadow-sm"><span className="text-2xl font-extrabold text-[#3155e8]">01</span><h3 className="mt-5 text-lg font-extrabold text-[#243653]">Upload your list</h3><p className="mt-2 text-sm leading-6 text-[#71809d]">Bring your CSV, XLSX, or TXT list into one simple workspace.</p></div><div className="rounded-2xl bg-white p-6 shadow-sm"><span className="text-2xl font-extrabold text-[#3155e8]">02</span><h3 className="mt-5 text-lg font-extrabold text-[#243653]">Verify every address</h3><p className="mt-2 text-sm leading-6 text-[#71809d]">Our engine checks syntax, domains, mailboxes, and risk signals.</p></div><div className="rounded-2xl bg-white p-6 shadow-sm"><span className="text-2xl font-extrabold text-[#3155e8]">03</span><h3 className="mt-5 text-lg font-extrabold text-[#243653]">Send with confidence</h3><p className="mt-2 text-sm leading-6 text-[#71809d]">Download a clean result and protect the reputation behind every campaign.</p></div></div></div></section>

    <section className="bg-white px-5 py-16 sm:px-8 sm:py-20"><div className="mx-auto max-w-5xl"><h2 className="text-center text-3xl font-extrabold tracking-[-0.04em]">Why Choose Us</h2><div className="mt-12 grid gap-8 md:grid-cols-3"><div className="rounded-2xl border border-slate-200 bg-gradient-to-br from-blue-50 to-cyan-50 p-6"><h3 className="text-lg font-extrabold text-[#243653]">Real-Time Verification</h3><p className="mt-3 text-sm leading-6 text-[#71809d]">Instant email validation using advanced SMTP, domain, and deliverability checks.</p></div><div className="rounded-2xl border border-slate-200 bg-gradient-to-br from-blue-50 to-cyan-50 p-6"><h3 className="text-lg font-extrabold text-[#243653]">Accurate Results</h3><p className="mt-3 text-sm leading-6 text-[#71809d]">Our engine uses billions of data points to give you the most accurate verification results.</p></div><div className="rounded-2xl border border-slate-200 bg-gradient-to-br from-blue-50 to-cyan-50 p-6"><h3 className="text-lg font-extrabold text-[#243653]">Easy Integration</h3><p className="mt-3 text-sm leading-6 text-[#71809d]">Connect with your favorite email marketing tools in just a few clicks.</p></div></div></div></section>

    <section className="bg-gradient-to-br from-[#263bd0] to-[#182a9f] px-5 py-16 text-white sm:px-8 sm:py-20"><div className="mx-auto max-w-5xl text-center"><h2 className="text-3xl font-extrabold tracking-[-0.04em]">Ready to get started?</h2><p className="mx-auto mt-4 max-w-2xl text-sm leading-6 text-blue-100">Join thousands of businesses using PureListVerifier to improve their email campaigns.</p><Link to="/register" className="mt-8 inline-flex items-center gap-2 rounded-lg bg-[#ff8250] px-6 py-3.5 text-xs font-extrabold shadow-xl hover:bg-[#ff956b]">Get 200,000 free verifications <ArrowRight size={15} /></Link></div></section>
  </main>;
}
