import { ArrowLeft, ArrowRight, LockKeyhole, ShieldCheck, UserRound } from "lucide-react";
import { Link } from "react-router-dom";
import { Brand } from "@/components/SiteHeader";

export default function Access() {
  return <main className="min-h-screen bg-[radial-gradient(circle_at_85%_10%,#e5eaff,transparent_28%),#fbfcff] px-5 py-6 text-[#172448] sm:px-8">
    <div className="mx-auto max-w-5xl"><header className="flex items-center justify-between"><Link to="/" className="rounded-lg focus:outline-none focus-visible:ring-2 focus-visible:ring-[#5164d8]"><Brand light={false} /></Link><Link to="/" className="inline-flex items-center gap-2 rounded-lg px-3 py-2 text-sm font-semibold text-slate-600 transition hover:text-[#3349be] focus:outline-none focus-visible:ring-2 focus-visible:ring-[#5164d8]"><ArrowLeft size={16} /> Back to welcome</Link></header>
      <section className="py-16 sm:py-24"><div className="mx-auto max-w-xl text-center"><p className="text-xs font-bold uppercase tracking-[.16em] text-[#5266cc]">PureListVerifier access</p><h1 className="mt-3 text-4xl font-extrabold tracking-[-.05em] text-[#122249] sm:text-5xl">Choose your access</h1><p className="mt-4 text-sm leading-6 text-slate-600">Select the right path to continue securely to PureListVerifier.</p></div><div className="mx-auto mt-10 grid max-w-4xl gap-5 md:grid-cols-2"><article className="rounded-2xl border-2 border-[#5366d5] bg-white p-7 shadow-xl shadow-indigo-100/70"><span className="grid h-12 w-12 place-items-center rounded-xl bg-[#edf0ff] text-[#4356c9]"><UserRound size={23} /></span><h2 className="mt-6 text-xl font-extrabold text-[#17284e]">User Access</h2><p className="mt-3 min-h-12 text-sm leading-6 text-slate-600">Verify emails and access your workspace.</p><div className="mt-7 grid gap-3"><Link to="/login?mode=user" className="inline-flex items-center justify-center gap-2 rounded-lg bg-[#3349be] px-4 py-3 text-sm font-bold text-white transition hover:bg-[#263aa5] focus:outline-none focus-visible:ring-2 focus-visible:ring-[#5164d8] focus-visible:ring-offset-2">Continue as User <ArrowRight size={16} /></Link><Link to="/register" className="inline-flex items-center justify-center rounded-lg border border-slate-200 px-4 py-3 text-sm font-bold text-[#314263] transition hover:bg-slate-50 focus:outline-none focus-visible:ring-2 focus-visible:ring-[#5164d8]">Create an account</Link></div></article>
        <article className="rounded-2xl border border-slate-200 bg-[#fbfcff] p-7"><span className="grid h-12 w-12 place-items-center rounded-xl bg-slate-100 text-slate-600"><ShieldCheck size={23} /></span><h2 className="mt-6 text-xl font-extrabold text-[#17284e]">Admin Access</h2><p className="mt-3 min-h-12 text-sm leading-6 text-slate-600">Manage users, access, credits and activity.</p><div className="mt-7"><Link to="/login?mode=admin" className="inline-flex w-full items-center justify-center gap-2 rounded-lg border border-slate-300 bg-white px-4 py-3 text-sm font-bold text-[#314263] transition hover:border-[#9ca9dd] hover:bg-slate-50 focus:outline-none focus-visible:ring-2 focus-visible:ring-[#5164d8]"><LockKeyhole size={16} /> Admin Login</Link></div><p className="mt-4 text-xs leading-5 text-slate-500">Admin access is verified after authentication.</p></article></div></section>
    </div>
  </main>;
}
